// <auto-generated />
using System;
using IS7012_FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IS7012_FinalProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260929214903_SeedEmployees")]
    partial class SeedEmployees
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("IS7012_FinalProject.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Main Office",
                            Name = "Accounting"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Main Office",
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Main Office",
                            Name = "Information Technology"
                        });
                });

            modelBuilder.Entity("IS7012_FinalProject.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("JobRoleId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "john.smith@company.com",
                            EmployeeNumber = "EMP001",
                            FirstName = "John",
                            HireDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobRoleId = 1,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Email = "sarah.johnson@company.com",
                            EmployeeNumber = "EMP002",
                            FirstName = "Sarah",
                            HireDate = new DateTime(2021, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobRoleId = 2,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            Email = "michael.brown@company.com",
                            EmployeeNumber = "EMP003",
                            FirstName = "Michael",
                            HireDate = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobRoleId = 3,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            Email = "emily.davis@company.com",
                            EmployeeNumber = "EMP004",
                            FirstName = "Emily",
                            HireDate = new DateTime(2022, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobRoleId = 1,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 1,
                            Email = "david.wilson@company.com",
                            EmployeeNumber = "EMP005",
                            FirstName = "David",
                            HireDate = new DateTime(2020, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobRoleId = 2,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 2,
                            Email = "jessica.taylor@company.com",
                            EmployeeNumber = "EMP006",
                            FirstName = "Jessica",
                            HireDate = new DateTime(2023, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobRoleId = 3,
                            LastName = "Taylor"
                        });
                });

            modelBuilder.Entity("IS7012_FinalProject.Models.JobRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JobRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Processes employee payroll",
                            Title = "Payroll Specialist"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Reviews and approves payroll",
                            Title = "Payroll Team Lead"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Supports employee administration",
                            Title = "HR Specialist"
                        });
                });

            modelBuilder.Entity("IS7012_FinalProject.Models.Employee", b =>
                {
                    b.HasOne("IS7012_FinalProject.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IS7012_FinalProject.Models.JobRole", "JobRole")
                        .WithMany("Employees")
                        .HasForeignKey("JobRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("JobRole");
                });

            modelBuilder.Entity("IS7012_FinalProject.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("IS7012_FinalProject.Models.JobRole", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
