// <auto-generated />
using System;
using IS7012_FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IS7012_FinalProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261001155309_AddPayrollEntitiesAndSeedData")]
    partial class AddPayrollEntitiesAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("IS7012_FinalProject.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Main Office",
                            Name = "Accounting"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Main Office",
                            Name = "Human Resources"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Main Office",
                            Name = "Information Technology"
                        });
                });

            modelBuilder.Entity("IS7012_FinalProject.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("JobRoleId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "john.smith@company.com",
                            EmployeeNumber = "EMP001",
                            FirstName = "John",
                            HireDate = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobRoleId = 1,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Email = "sarah.johnson@company.com",
                            EmployeeNumber = "EMP002",
                            FirstName = "Sarah",
                            HireDate = new DateTime(2021, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobRoleId = 2,
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            Email = "michael.brown@company.com",
                            EmployeeNumber = "EMP003",
                            FirstName = "Michael",
                            HireDate = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobRoleId = 3,
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 1,
                            Email = "emily.davis@company.com",
                            EmployeeNumber = "EMP004",
                            FirstName = "Emily",
                            HireDate = new DateTime(2022, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobRoleId = 1,
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 1,
                            Email = "david.wilson@company.com",
                            EmployeeNumber = "EMP005",
                            FirstName = "David",
                            HireDate = new DateTime(2020, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobRoleId = 2,
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 2,
                            Email = "jessica.taylor@company.com",
                            EmployeeNumber = "EMP006",
                            FirstName = "Jessica",
                            HireDate = new DateTime(2023, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            JobRoleId = 3,
                            LastName = "Taylor"
                        });
                });

            modelBuilder.Entity("IS7012_FinalProject.Models.JobRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("JobRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Processes employee payroll",
                            Title = "Payroll Specialist"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Reviews and approves payroll",
                            Title = "Payroll Team Lead"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Supports employee administration",
                            Title = "HR Specialist"
                        });
                });

            modelBuilder.Entity("IS7012_FinalProject.Models.PayrollPeriod", b =>
                {
                    b.Property<int>("PayrollPeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("PayrollPeriodId");

                    b.ToTable("PayrollPeriods");

                    b.HasData(
                        new
                        {
                            PayrollPeriodId = 1,
                            EndDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsClosed = false,
                            StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PayrollPeriodId = 2,
                            EndDate = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsClosed = false,
                            StartDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PayrollPeriodId = 3,
                            EndDate = new DateTime(2026, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsClosed = false,
                            StartDate = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("IS7012_FinalProject.Models.PayrollRecord", b =>
                {
                    b.Property<int>("PayrollRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AdditionalEarnings")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Deductions")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PayrollPeriodId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreparedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PreparedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("SalaryPackageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("PayrollRecordId");

                    b.HasIndex("PayrollPeriodId");

                    b.HasIndex("SalaryPackageId");

                    b.HasIndex("EmployeeId", "PayrollPeriodId")
                        .IsUnique();

                    b.ToTable("PayrollRecords");
                });

            modelBuilder.Entity("IS7012_FinalProject.Models.SalaryPackage", b =>
                {
                    b.Property<int>("SalaryPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Allowance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SalaryPackageId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("SalaryPackages");

                    b.HasData(
                        new
                        {
                            SalaryPackageId = 1,
                            Allowance = 1000m,
                            BasicSalary = 6000m,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 1
                        },
                        new
                        {
                            SalaryPackageId = 2,
                            Allowance = 1500m,
                            BasicSalary = 9000m,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 2
                        },
                        new
                        {
                            SalaryPackageId = 3,
                            Allowance = 1000m,
                            BasicSalary = 6500m,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 3
                        },
                        new
                        {
                            SalaryPackageId = 4,
                            Allowance = 800m,
                            BasicSalary = 5500m,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EffectiveTo = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4
                        },
                        new
                        {
                            SalaryPackageId = 5,
                            Allowance = 900m,
                            BasicSalary = 6000m,
                            EffectiveFrom = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 4
                        },
                        new
                        {
                            SalaryPackageId = 6,
                            Allowance = 1500m,
                            BasicSalary = 9500m,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 5
                        },
                        new
                        {
                            SalaryPackageId = 7,
                            Allowance = 900m,
                            BasicSalary = 6200m,
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeId = 6
                        });
                });

            modelBuilder.Entity("IS7012_FinalProject.Models.Employee", b =>
                {
                    b.HasOne("IS7012_FinalProject.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IS7012_FinalProject.Models.JobRole", "JobRole")
                        .WithMany("Employees")
                        .HasForeignKey("JobRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("JobRole");
                });

            modelBuilder.Entity("IS7012_FinalProject.Models.PayrollRecord", b =>
                {
                    b.HasOne("IS7012_FinalProject.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IS7012_FinalProject.Models.PayrollPeriod", "PayrollPeriod")
                        .WithMany("PayrollRecords")
                        .HasForeignKey("PayrollPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IS7012_FinalProject.Models.SalaryPackage", "SalaryPackage")
                        .WithMany("PayrollRecords")
                        .HasForeignKey("SalaryPackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PayrollPeriod");

                    b.Navigation("SalaryPackage");
                });

            modelBuilder.Entity("IS7012_FinalProject.Models.SalaryPackage", b =>
                {
                    b.HasOne("IS7012_FinalProject.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IS7012_FinalProject.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("IS7012_FinalProject.Models.JobRole", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("IS7012_FinalProject.Models.PayrollPeriod", b =>
                {
                    b.Navigation("PayrollRecords");
                });

            modelBuilder.Entity("IS7012_FinalProject.Models.SalaryPackage", b =>
                {
                    b.Navigation("PayrollRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
